spring:
  profiles:
    active: dev
  web:
    resources:
      add-mappings: false
api:
  endpoint:
    base-url: /api/v1
server:
  port: 80
  ai:
    openai:
      endpoint: ${AI_OPENAI_ENDPOINT:https://api.openai.com/v1/chat/completions}
      api-key: ${AI_OPENAI_API_KEY:YOUR_API_KEY}